### ISSUE TITLE
Enhancement: Updated Bad Words List

### ISSUE THREAD

**Issue by dsposito** [listenrightmeow/pottymouth#1]
Might be worth copying over some of the bad words on this list and or adding multi lang support:

https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

**Comment by listenrightmeow** [comment]
https://jsperf.com/object-hasownproperty-vs-array-indexof/2

Only problem I have with this is that running a dictionary lookup in an object via hasOwnProperty is close to 275 times faster than doing a standard lookup in a flat array.

I, or somebody else, can probably build this functionality to convert an array dictionary (of their choice) to an object as part of a build process on the project.

**Comment by listenrightmeow** [comment]
https://github.com/listenrightmeow/pottymouth/commit/97494d8d96da9c767a2c1aef35aec6d62ba58e98#diff-04c6e90faac2675aa89e2176d2eec7d8R59

I defaulted the dictionary for the plugin to the en file in the repo you listed.

I haven't tested all of the edge cases for overriding, e.g. picking another json file or picking a file that contains a javascript array. I'm sure if this library is used somebody will open an issue at that point.

```
grunt --dictionary=https://raw.githubusercontent.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en --filetype=txt
```

**Comment by dsposito** [comment]
Fancy! :+1:
